"""ESP32 projection — embedded-friendly surface.

Surface (sketch; full codegen in Phase 5):
- Generate C / Arduino-sketch code that talks to the port
- CoAP or WebSocket transport (CoAP preferred for low-RAM)
- Signed receipts (HMAC-SHA256 with device-specific key)
- Latency budget: 50ms
- Memory budget: < 32 KB

The codegen produces an Arduino library the user includes in their sketch:

    #include <quilt_port_esp32.h>
    QuiltPortClient port(WIFI_SSID, WIFI_PASS, "quilt-port-casey-esp32",
                         "https://port.workers.dev");
    auto reading = port.get_cell("sensor/temperature");
    port.record(sensor_reading);  // signed receipt
"""
from __future__ import annotations

from typing import Any, Dict


def codegen_arduino_sketch(device_id: str, port_endpoint: str, cells: list) -> str:
    """Generate an Arduino sketch template for an ESP32 device.

    Args:
        device_id: the user's port identifier (e.g. 'quilt-port-casey-esp32')
        port_endpoint: the port's URL (e.g. 'https://port.workers.dev')
        cells: list of cell IDs the device will read/write

    The generated sketch is a starting point — users fill in their sensor
    reads and the cells they want to record. The library handles auth,
    signing, and the witness chain.
    """
    cell_setup_lines = []
    cell_read_lines = []
    for c in cells:
        cell_setup_lines.append(f'  cells.cell("{c}");')
        cell_read_lines.append(f'  // auto-read {c}: call cells.read("{c}")')

    return f"""// Auto-generated by quilt-port Phase 5 codegen.
// Edit freely; this is a template you can adapt.

#include <WiFi.h>
#include <quilt_port_esp32.h>

const char* WIFI_SSID   = "YOUR_WIFI_SSID";
const char* WIFI_PASS   = "YOUR_WIFI_PASSWORD";
const char* PORT_ID     = "{device_id}";
const char* PORT_URL    = "{port_endpoint}";

QuiltPortClient port(PORT_ID, PORT_URL);

void setup() {{
  Serial.begin(115200);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  while (WiFi.status() != WL_CONNECTED) {{
    delay(500); Serial.print(".");
  }}
  Serial.println("connected");

  // Declare the cells this device will read/write.
{chr(10).join(cell_setup_lines)}

  // Authenticate (first call sets up the device key + signed receipts).
  port.authenticate();

  // Optional: bind to a witness chain for offline buffering.
  port.bind_chain_size(64);  // keep last 64 witnesses in RAM
}}

void loop() {{
  // 1. Read any subscribed cells.
{chr(10).join(cell_read_lines)}

  // 2. Read your actual sensor.
  float temperature = read_temperature();  // user code

  // 3. Record the reading (witnessed, signed).
  port.record("sensor/temperature", temperature);

  // 4. Optional: promote local chain to canon (every N reads).
  static int tick = 0;
  if (++tick % 100 == 0) {{
    port.promote();
  }}

  delay(1000);
}}
"""


def codegen_verilog_module(port_id: str) -> str:
    """Generate a Verilog module skeleton for FPGA-based quilt ports.

    Args:
        port_id: the user's port identifier

    The Verilog module is a hardware translation of the Port's cell-graph,
    suitable for synthesis on FPGAs. Witness chain stored in BRAM.
    """
    return f"""// Auto-generated by quilt-port Phase 5 codegen.
// Hardware-descriptor for an FPGA-port.

module quilt_port_{port_id.replace("-", "_")} #(
    parameter CLOCK_FREQ_HZ = 50_000_000
) (
    input  wire        clk,
    input  wire        rst_n,
    // Cells
    input  wire [31:0] cell_data_in,
    output wire [31:0] cell_data_out,
    // Witness chain (BRAM-backed)
    output wire [15:0] witness_count,
    output wire [63:0] witness_last_hash
);

    // Stub: real implementation lives in Phase 5 (ground-up).
    //
    // Idea: each cell is a 32-bit register with a 64-bit content hash.
    // Witness chain is a BRAM ring buffer; FNV1a-64 hashing in hardware.
    // The "promote" operation is a hardware-mediated state transition.

    assign witness_count = 16'd0;
    assign witness_last_hash = 64'd0;
    assign cell_data_out = cell_data_in;

endmodule
"""
